apiVersion: v1
kind: Service
metadata:
  name: update
spec:
  selector:
    app: update
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update
  template:
    metadata:
      labels:
        app: update
    spec:
      containers:
        - name: update
          image: update:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: grpc
          env:
            - name: UPDATE_ADDRESS
              value: ":8080"

            - name: DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_ADDRESS

            - name: XKCD_URL
              value: "https://xkcd.com"
            - name: XKCD_CONCURRENCY
              value: "64"

            - name: WORDS_ADDRESS
              value: "words:8080"
            - name: BROKER_ADDRESS
              value: "nats://nats:4222"

          volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: update-config
