apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: comics

resources:
  - ../../base

patches:
  - path: api-nodeport.yaml

secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true
